WIP: clarify discourse administration
NixOS/org pull request #44
Opened 2024-12-02 22:27 UTC by Lassulus

this is a proposal, I still need to clarify the roles with everyone :)

2025-01-23 23:58 UTC, jtojnar approved these changes

2025-01-24 00:16 UTC, winterqt approved these changes

2025-01-26 14:13 UTC, fpletz approved these changes

2025-01-26 18:46 UTC, Gabriella439 approved these changes

2025-01-26 18:47 UTC, Gabriella439 commented on doc/discourse.md
> +The administration is handled by 2 Moderators, 1-2 representatives from the SC and the appointed Administrators from Flying Circus and the Infra Team.
```suggestion
The administration is handled by 2 Moderators, 1-2 representatives from the SC and the following Administrators from Flying Circus and the Infra Team.
```

2025-01-26 18:47 UTC, roberth commented on doc/discourse.md
> +The administration is handled by 2 Moderators, 1-2 representatives from the SC and the appointed Administrators from Flying Circus and the Infra Team.
```suggestion
The administration is handled by 2 Moderators, 1-2 representatives from the Steering Committee and the following Administrators from Flying Circus and the Infra Team.
```

2025-01-26 18:50 UTC, Ericson2314 approved these changes

2025-01-26 19:15 UTC, infinisil commented on .github/CODEOWNERS
> +/doc/discourse.md @NixOS/steering @mweinelt @picnoir @lassulus
Because all Discourse admins can change who's an admin, all of them should be listed here and informed about it, to make sure they don't change administrators without a PR.

2025-01-26 19:21 UTC, infinisil requested changes

2025-01-26 19:21 UTC, infinisil commented on .github/CODEOWNERS
> +/doc/discourse.md @NixOS/steering @mweinelt @picnoir @lassulus
```suggestion
/doc/discourse.md @NixOS/steering @mweinelt @picnoir @lassulus @jtojnar @ctheune @dpausp
```

Also @jtojnar because not being part of the SC anymore doesn't automatically mean he won't be an admin anymore.

Ping @ctheune, @dpausp, @picnoir and @mweinelt

2025-01-26 19:21 UTC, infinisil commented on doc/discourse.md
> +- https://discourse.nixos.org/u/dpausp
```suggestion
Flying Circus Administrators:
- @ctheune
- @dpausp
```

2025-01-26 19:21 UTC, jtojnar commented on doc/discourse.md
> +The administration is handled by 2 Moderators, 1-2 representatives from the Steering Committee and the following Administrators from Flying Circus (Discourse hosting provider) and the Infra Team.
That Flying Circus is the hoster is already mentioned above the fold.

2025-01-26 19:25 UTC, Ericson2314 commented on doc/discourse.md
> +The administration is handled by 2 Moderators, 1-2 representatives from the Steering Committee and the following Administrators from Flying Circus (Discourse hosting provider) and the Infra Team.
```suggestion
The administration is handled by 2 Moderators, 1-2 representatives from the Steering Committee, and the following Administrators from the sponsoring hosting provider (Flying Circus as mentioned above) and the Infra Team.
```
@jtojnar this is the direction I sort of felt like going in.

2025-01-31 03:55 UTC, infinisil approved these changes

2025-01-31 06:55 UTC, Lassulus commented
just waiting on @mweinelt to actually make the people admins, afterwards this can be merged (also by @mweinelt :))

2025-01-31 13:51 UTC, Lassulus commented
ok, everyone except @jtojnar is admin now, he just needs to enable 2FA and we can also do that and merge this

2025-01-31 15:09 UTC, jtojnar commented
Thanks, enabled that.

2025-01-31 15:14 UTC, merged